### ISSUE TITLE
May I ask, could you give me the plugin of IDA pro to extract the ACFG?

### ISSUE THREAD

**Issue by CoderHiro** [xiaojunxu/gemini_reorganize#6]
I found that there are only the results of the ACFGs in this project. And now I want to extract the ACFGs of other files. Could you give me the plugin to extract the ACFGs or tell me where can I get this plugin? Thank you.

**Comment by yasong** [comment]
Did you get the code to extract ACFGs features?

**Comment by yizhicheng1** [comment]
May I ask if you have solved the problem you raised now, I also want to know how to extract ACFG
